-- Foundation tables, ported from kasway-v2-api Lucid migrations to SQLite.
-- Type mapping: increments -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- timestamp -> TEXT (ISO8601), boolean -> BIGINT (0/1), jsonb -> TEXT.

-- 1761040248938_create_users_table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  avatar_url TEXT,
  onboarded BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT
);

-- 1761040248940_create_access_tokens_table
CREATE TABLE auth_access_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tokenable_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  name TEXT,
  hash TEXT NOT NULL,
  abilities TEXT NOT NULL,
  created_at TEXT,
  updated_at TEXT,
  last_used_at TEXT,
  expires_at TEXT
);

-- 1778790000000_create_api_keys_table
CREATE TABLE api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  prefix TEXT NOT NULL UNIQUE,
  key_hash TEXT NOT NULL UNIQUE,
  scopes TEXT NOT NULL,
  last_used_at TEXT,
  expires_at TEXT,
  revoked_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX api_keys_user_id_index ON api_keys(user_id);
CREATE INDEX api_keys_prefix_index ON api_keys(prefix);
CREATE INDEX api_keys_revoked_at_index ON api_keys(revoked_at);

-- 1761063867627_create_currencies_table
CREATE TABLE currencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  symbol TEXT NOT NULL,
  country TEXT NOT NULL,
  locale TEXT NOT NULL,
  created_at TEXT,
  updated_at TEXT
);
