-- teams (1761063867628_create_teams_table)
CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  currency_id BIGINT REFERENCES currencies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT,
  updated_at TEXT
);

-- team_members (1761065147296_create_team_members_table)
CREATE TABLE team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  avatar_url TEXT,
  status TEXT NOT NULL DEFAULT 'invited',
  invitation_sent_at TEXT,
  joined_at TEXT,
  left_at TEXT,
  is_online BIGINT NOT NULL DEFAULT 0,
  role TEXT NOT NULL,
  password TEXT,
  created_at TEXT,
  updated_at TEXT
);

-- team_member_auth_access_tokens (1761065147297_create_team_member_access_tokens_table)
CREATE TABLE team_member_auth_access_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tokenable_id BIGINT NOT NULL REFERENCES team_members(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  name TEXT,
  hash TEXT NOT NULL,
  abilities TEXT NOT NULL,
  created_at TEXT,
  updated_at TEXT,
  last_used_at TEXT,
  expires_at TEXT
);
