-- Payment/credit/observation ledger tables consumed by derivePaymentStatus,
-- the chain observer, and the KPR-1 explorer.

CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  metadata TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payments_invoice_id_index ON payments(invoice_id);

CREATE TABLE payment_credits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  amount BIGINT NOT NULL DEFAULT 0,
  user_id BIGINT,
  payment_observation_id BIGINT,
  network TEXT,
  asset_id TEXT,
  credited_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payment_credits_invoice_id_index ON payment_credits(invoice_id);

CREATE TABLE payment_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  status TEXT NOT NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  confirmations BIGINT NOT NULL DEFAULT 0,
  network TEXT,
  asset_id TEXT,
  tx_id TEXT,
  output_index BIGINT,
  payment_address TEXT,
  payer_address TEXT,
  block_hash TEXT,
  block_daa_score BIGINT,
  -- KPR-1 explorer reads observation metadata (kpr1.outputs / kpr1.intentId /
  -- kpr1.scriptHash).
  metadata TEXT,
  accepted_at TEXT,
  matched_at TEXT,
  settled_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payment_observations_invoice_id_index ON payment_observations(invoice_id);
