-- webhook_endpoints / webhook_events / webhook_deliveries
-- (1778790000001 + control fields 1779000000008 + store_id from stores migration).

CREATE TABLE webhook_endpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  store_id BIGINT REFERENCES stores(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  events TEXT NOT NULL,
  signing_secret TEXT NOT NULL,
  is_active BIGINT NOT NULL DEFAULT 1,
  paused_at TEXT,
  secret_rotated_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX webhook_endpoints_user_index ON webhook_endpoints(user_id);
CREATE INDEX webhook_endpoints_user_active_index ON webhook_endpoints(user_id, is_active);

CREATE TABLE webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  store_id BIGINT REFERENCES stores(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  payload TEXT NOT NULL,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX webhook_events_user_index ON webhook_events(user_id);
CREATE INDEX webhook_events_user_type_index ON webhook_events(user_id, event_type);

CREATE TABLE webhook_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_event_id BIGINT NOT NULL REFERENCES webhook_events(id) ON DELETE CASCADE,
  webhook_endpoint_id BIGINT NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  attempt_count BIGINT NOT NULL DEFAULT 0,
  response_status BIGINT,
  response_body TEXT,
  error TEXT,
  is_replay BIGINT NOT NULL DEFAULT 0,
  last_attempted_at TEXT,
  next_attempt_at TEXT,
  delivered_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX webhook_deliveries_event_index ON webhook_deliveries(webhook_event_id);
CREATE INDEX webhook_deliveries_endpoint_index ON webhook_deliveries(webhook_endpoint_id);
CREATE INDEX webhook_deliveries_status_index ON webhook_deliveries(status);
