-- payment_tenant_settings (1779000000012 + confirmation_policy 1779000000017).
CREATE TABLE payment_tenant_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  enabled_payment_modules TEXT NOT NULL DEFAULT '[]',
  allowed_networks TEXT NOT NULL DEFAULT '["tn10"]',
  allowed_assets TEXT NOT NULL DEFAULT '["KAS"]',
  default_export_retention_days BIGINT NOT NULL DEFAULT 7,
  webhook_retry_profile TEXT NOT NULL DEFAULT 'balanced',
  exception_notification_categories TEXT NOT NULL DEFAULT '{}',
  allowed_manual_adjustment_kinds TEXT NOT NULL DEFAULT '[]',
  confirmation_policy TEXT,
  created_at TEXT,
  updated_at TEXT,
  UNIQUE (user_id)
);
