-- payment_reporting_categories + payment_accounting_profiles
-- (subset of 1779000000018_create_financial_reporting_tables).
CREATE TABLE payment_reporting_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  code TEXT NOT NULL,
  type TEXT NOT NULL,
  calculation_mode TEXT NOT NULL DEFAULT 'manual',
  rate TEXT,
  amount BIGINT,
  is_active BIGINT NOT NULL DEFAULT 1,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payment_reporting_categories_user_index ON payment_reporting_categories(user_id);

CREATE TABLE payment_accounting_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  account_codes TEXT NOT NULL DEFAULT '{}',
  category_mappings TEXT NOT NULL DEFAULT '{}',
  currency_handling TEXT NOT NULL DEFAULT 'source',
  date_format TEXT NOT NULL DEFAULT 'yyyy-MM-dd',
  timezone TEXT NOT NULL DEFAULT 'UTC',
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payment_accounting_profiles_user_index ON payment_accounting_profiles(user_id);
