-- Subscription Pocket autopay: one covenant "cell" per subscription.
--
-- The customer funds a SubscriptionV1 P2SH covenant holding several periods'
-- worth of value; the keeper claims one period at a time (CSV relative lock),
-- the remainder self-replicates back to the covenant address. `params_json`
-- snapshots everything needed to recompile the exact covenant (payouts,
-- period_daa, sweep_threshold, keeper pubkey, customer refund address).
--
-- state: awaiting_funding | active | claiming (transient, keeper-owned)
--        | past_due (due cycle but insufficient funds / swept empty)
--        | withdrawn | cancelled
CREATE TABLE subscription_cells (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id BIGINT NOT NULL UNIQUE REFERENCES subscriptions(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  network TEXT NOT NULL,
  covenant_address TEXT NOT NULL,
  params_json TEXT NOT NULL,
  claim_total BIGINT NOT NULL,
  refund_address TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'awaiting_funding',
  -- JSON array of funding tx ids the customer DECLARED (via the public autopay
  -- endpoint). Only UTXOs from these txids — or the remainder of our own last
  -- claim — are ever recognized as cell funds; third-party sends are ignored.
  recorded_funding_txids TEXT NOT NULL DEFAULT '[]',
  active_outpoint_txid TEXT,
  active_outpoint_index BIGINT,
  active_amount BIGINT,
  last_claim_tx_id TEXT,
  last_claim_at TEXT,
  -- Pending withdraw draft (prepare -> submit): destination + expected sighash
  -- so submit can detect a stale draft after UTXO churn.
  withdraw_destination TEXT,
  withdraw_sighash TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX subscription_cells_state_index ON subscription_cells(state);

-- The biller scans due subscriptions every tick.
CREATE INDEX subscriptions_due_index ON subscriptions(status, next_billing_at);
