-- Async/synchronous CSV export manifests (PaymentOperationsExportService) plus
-- the extra ledger columns the CSV builders read. The minimal observation/credit
-- tables from 0006 only carried what derivePaymentStatus needed; the export CSVs
-- emit the full row shape, so we widen them here (additive, nullable columns).

CREATE TABLE payment_operation_exports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  format TEXT NOT NULL DEFAULT 'csv',
  profile_id BIGINT,
  filters TEXT NOT NULL DEFAULT '{}',
  mapping_metadata TEXT NOT NULL DEFAULT '{}',
  row_count BIGINT NOT NULL DEFAULT 0,
  checksum TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  storage_disk TEXT,
  storage_path TEXT,
  content_type TEXT,
  byte_size BIGINT,
  expires_at TEXT,
  error TEXT,
  actor_type TEXT NOT NULL DEFAULT 'merchant',
  actor_id TEXT,
  generated_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payment_operation_exports_user_index ON payment_operation_exports(user_id, generated_at);

-- Widen payment_observations to the full export row shape.
ALTER TABLE payment_observations ADD COLUMN network TEXT;
ALTER TABLE payment_observations ADD COLUMN asset_id TEXT;
ALTER TABLE payment_observations ADD COLUMN tx_id TEXT;
ALTER TABLE payment_observations ADD COLUMN output_index BIGINT;
ALTER TABLE payment_observations ADD COLUMN payment_address TEXT;
ALTER TABLE payment_observations ADD COLUMN payer_address TEXT;
ALTER TABLE payment_observations ADD COLUMN block_hash TEXT;
ALTER TABLE payment_observations ADD COLUMN block_daa_score BIGINT;
ALTER TABLE payment_observations ADD COLUMN matched_at TEXT;
ALTER TABLE payment_observations ADD COLUMN settled_at TEXT;

-- Widen payment_credits to the full export row shape.
ALTER TABLE payment_credits ADD COLUMN user_id BIGINT;
ALTER TABLE payment_credits ADD COLUMN payment_observation_id BIGINT;
ALTER TABLE payment_credits ADD COLUMN network TEXT;
ALTER TABLE payment_credits ADD COLUMN asset_id TEXT;
ALTER TABLE payment_credits ADD COLUMN credited_at TEXT;
