-- Generated financial statements (PaymentStatementService). The artifact bytes
-- live on a storage disk in Adonis; the port regenerates the deterministic JSON
-- artifact on demand from `totals`, so no blob column is needed.

CREATE TABLE payment_statements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'generated',
  totals TEXT NOT NULL DEFAULT '{}',
  checksum TEXT NOT NULL DEFAULT '',
  storage_disk TEXT,
  storage_path TEXT,
  content_type TEXT,
  byte_size BIGINT,
  generated_at TEXT,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX payment_statements_user_period_index ON payment_statements(user_id, period_start);
