-- Public waitlist signups (WaitlistController). Captcha + per-IP rate limiting
-- live in the handler; here we enforce email uniqueness and store only a hashed
-- IP (never the raw address) for abuse tracking. Timestamps are TEXT ISO8601 to
-- match the rest of the schema (Lucid autoCreate shape via now_iso()).

CREATE TABLE waitlist_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  ip_hash TEXT,
  user_agent TEXT,
  turnstile_token TEXT,
  source TEXT,
  created_at TEXT
);
CREATE INDEX waitlist_entries_ip_hash_index ON waitlist_entries(ip_hash, created_at);
